version: "3"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: universal-next
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - internal_network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./dist/nginx:/etc/nginx/conf.d/
    networks:
      - internal_network
      - external_network

networks:
  external_network:
  internal_network:
    internal: true